### ISSUE TITLE
compilation error in `lx200stargo.cpp` 

### ISSUE THREAD

**Issue by wuyuanyi135** [indilib/indi-3rdparty#411]
caused by commit fe71ec0f00f58d0ed75a04042e009e7df4e53bf5 that removed the `LocalSiderealTime` function.
https://github.com/indilib/indi-3rdparty/blob/fe71ec0f00f58d0ed75a04042e009e7df4e53bf5/indi-avalon/lx200stargo.cpp#L1106

**Comment by knro** [comment]
Compiles fine here with latest INDI. Please double check.
