### ISSUE TITLE
indi_gphoto does not compile with libraw-0.20

### ISSUE THREAD

**Issue by knallio** [indilib/indi-3rdparty#173]
Compiling indi-gphoto with libraw-0.20 throws an error because the data structures have changed:

```
.../indi-3rdparty/indi-gphoto/gphoto_driver.cpp:870:39: error: 'struct libraw_imgother_t' has no member named 'SensorTemperature'
  870 |             if (lib_raw.imgdata.other.SensorTemperature > -273.15f)
      |                                       ^~~~~~~~~~~~~~~~~
.../indi-3rdparty/indi-gphoto/gphoto_driver.cpp:871:66: error: 'struct libraw_imgother_t' has no member named 'SensorTemperature'
  871 |                 gphoto->last_sensor_temp = lib_raw.imgdata.other.SensorTemperature;
      |                                                                  ^~~~~~~~~~~~~~~~~
.../indi-3rdparty/indi-gphoto/gphoto_driver.cpp:872:44: error: 'struct libraw_imgother_t' has no member named 'CameraTemperature'
  872 |             else if (lib_raw.imgdata.other.CameraTemperature > -273.15f)
      |                                            ^~~~~~~~~~~~~~~~~
.../indi-3rdparty/indi-gphoto/gphoto_driver.cpp:873:66: error: 'struct libraw_imgother_t' has no member named 'CameraTemperature'
  873 |                 gphoto->last_sensor_temp = lib_raw.imgdata.other.CameraTemperature;
```

By changing `lib_raw.imgdata.other.SensorTemperature` to `lib_raw.imgdata.makernotes.common.SensorTemperature` it compiles again, but I still have to test if everything works. If you want I could open a pull request with the changes.
